// Copyright IBM Corp. 2026
// SPDX-License-Identifier: BUSL-1.1

package interfaces

import "time"

// SealConfig is a dependency-free mirror of vault.SealConfig. It carries
// the same fields, in the same order, so that call sites on either side of
// the vault/interfaces boundary can convert between the two with a plain
// field-by-field copy (or an unsafe cast, if the layouts are kept in sync).
//
// This type is defined locally, rather than imported from the vault
// package, because the vault package is exactly what this package must
// remain independent of.
type SealConfig struct {
	// Type is the seal type, for sanity checking. See vault.SealConfigType
	// for valid values.
	Type string `json:"type" mapstructure:"type"`

	// SecretShares is the number of shares the secret is split into. This is
	// the N value of Shamir.
	SecretShares int `json:"secret_shares" mapstructure:"secret_shares"`

	// SecretThreshold is the number of parts required to open the vault.
	// This is the T value of Shamir.
	SecretThreshold int `json:"secret_threshold" mapstructure:"secret_threshold"`

	// PGPKeys is the array of public PGP keys used, if requested, to encrypt
	// the output unseal tokens. If provided, it sets the value of
	// SecretShares. Ordering is important.
	PGPKeys []string `json:"pgp_keys" mapstructure:"pgp_keys"`

	// Nonce is a nonce generated by Vault used to ensure that when unseal
	// keys are submitted for a rekey operation, the rekey operation itself
	// is the one intended. This prevents hijacking of the rekey operation,
	// since it is unauthenticated.
	Nonce string `json:"nonce" mapstructure:"nonce"`

	// Backup indicates whether or not a backup of PGP-encrypted unseal keys
	// should be stored after successful rekeying.
	Backup bool `json:"backup" mapstructure:"backup"`

	// StoredShares is how many keys to store, for seals that support
	// storage. Always 0 or 1.
	StoredShares int `json:"stored_shares" mapstructure:"stored_shares"`

	// RekeyProgress stores the progress of the rekey operation (key shares).
	RekeyProgress [][]byte `json:"-"`

	// VerificationRequired indicates that after a rekey, validation must be
	// performed (via providing shares from the new key) before the new key
	// is actually installed.
	VerificationRequired bool `json:"-"`

	// VerificationKey is the new key that will be rolled to after
	// successful validation.
	VerificationKey []byte `json:"-"`

	// VerificationNonce stores the current operation nonce for
	// verification.
	VerificationNonce string `json:"-"`

	// VerificationProgress stores the progress of the verification
	// operation (key shares).
	VerificationProgress [][]byte `json:"-"`

	// Name is the name provided in the seal configuration to identify the
	// seal.
	Name string `json:"name" mapstructure:"name"`

	// Created is the time of creation in UTC.
	Created time.Time `json:"-"`
}

// StorageEntry is a dependency-free mirror of sdk/physical.Entry, used by
// CoreAccess's physical storage accessor methods so that this package does
// not need to import the sdk module.
type StorageEntry struct {
	// Key is the storage path the entry is stored under.
	Key string

	// Value is the raw (already encrypted, where applicable) entry value.
	Value []byte

	// SealWrap indicates whether the entry is seal-wrapped.
	SealWrap bool

	// ValueHash is only used in replication.
	ValueHash []byte
}
