name: Dependency Audit

# cancel existing runs of the same workflow on the same ref
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - 'main'
      - 'release/**'
      - 'ce/**'

jobs:
  check-archived-deps:
    runs-on: ${{ github.repository == 'hashicorp/vault' && 'ubuntu-latest' || fromJSON('["self-hosted","ubuntu-22.04-x64"]') }}
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Check for archived/deprecated Go dependencies
        run: ./.github/scripts/check-archived-deps.sh go.mod internalshared/go.mod
